config/routes.rb
Rails.application.routes.draw do
  root 'links#new'
  # get 'links#index'
  # get 'params[:id]' => 'links#show'
  get ':id' => 'links#show'
  resources :links
  # get 'alt/:shortURL' => 'link#show_alt'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link.rb
class Link < ApplicationRecord
  # validates :shortURL, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
    before_action :set_link, only: [:show]
    # before_action :set_link_alt, only: :show_alt
    # before_action :create_shortURL, only: :new

    def index
      @link = Link.all
    end

    def show
      redirect_to @link.longURL
    end
    #
    # def show_alt
    #   redirect_to @link.longURL
    # end


    def new
      @link = Link.new
    end

    def create
      @link = Link.new(link_params)
      if @link.save
        redirect_to links_path, notice: 'Link shortened!'
      else
        render :new
      end
    end

    private
    def link_params
      params.require(:link).permit(:longURL)
    end

    def set_link
      @link = Link.find(params[:id])
    end

    # def set_link_alt
    #   @link = Link.find_by(shortURL: params[:shortURL])
    # end

    # def create_shortURL
    #   @shortURL = LinkGenerator.generate
    # end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/link_helper.rb
module LinkHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UrlShortener</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/links/_form.html.erb
<%= form_for(@link) do |f| %>
  <div class="field">
    <%= f.label :longURL %>
    <%= f.text_field :longURL %>
  </div>
  <div class="field">
  <%= f.hidden_field :shortURL, value: @shortURL%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/links/index.html.erb
<p id="notice"><%= notice %></p>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Original</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  <% @link.each do |url| %>
      <tr>
        <td><%= url.id %></td>
        <td><%= url.longURL %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<p>Visit https://peaceful-mesa-34942.herokuapp.com/(id) to be redirected.
</p>

app/views/links/new.html.erb
<p id="notice"><%= notice %></p>
<p>Enter a url that you would like shortened!
<%= render 'form' %>
<%#= link_to 'Index', link_index_path %>
<p>Visit https://peacefull-mesa-34942.herokuapp.com/(id) to be redirected.
</p>